---
title: "Peak Report"
output: html_notebook
params:
  data_path: APA_BEN_BAM_TP1_BP2_WOB9
  output_file: NULL
  popgen_prefix: MIC4273_HAP2_NEWREF_MSU618_all_fish_all_sites
  MAF_thresh: 0.05
  pops: ["APA","BEN","BAM"]
---

```{r setup, include=FALSE}
root<-rprojroot::find_root(".git/index")
knitr::opts_knit$set(root.dir = root)
require(tidyverse)
library(patchwork)
library(data.table)
library(reshape2)
library(stringr)
library(scales)      # For percent_format in scale_y_continuous
require(GenomicRanges)
require(rtracklayer)
require(gggenes)
require(rentrez)
require(rlang)

source(file.path(root,"code","06_Association","gemma_gwas_functions.R"))
source(file.path(root,"code","08_Peak_Analysis","peak_analysis_functions.R"))

```

## Data Loading

### Load the Genotypic Data
```{r}
geno_path<-file.path(root,"output_data","08_Peak_Analysis",params$data_path,paste0(params$data_path,".bin.pos.genos"))
peaks_path<-file.path(root,"output_data","06_Association",params$data_path,paste0(params$data_path,"_PEAKS.bed"))
logp_path<-file.path(root,"output_data","06_Association",params$data_path,paste0(params$data_path,"_SNPS_IN_PEAKS_TOP250.txt"))
dxy_file=file.path(root,"output_data/05_PopGen/",paste0(params$popgen_prefix,"_dxy.txt"))
fst_file=file.path(root,"output_data/05_PopGen/",paste0(params$popgen_prefix,"_fst.txt"))
pi_file=file.path(root,"output_data/05_PopGen/",paste0(params$popgen_prefix,"_pi.txt"))
tajd_file=file.path(root,"output_data/05_PopGen/",paste0(params$popgen_prefix,"_tajd.txt"))


df.genos<-read.table(geno_path,header=T)

long_genotype <- df.genos %>%
  pivot_longer(
    cols = -c(CHROM, POS, REF, ALT), # Exclude the first four columns
    names_to = "name",          # Column for the new 'name' variable
    values_to = "geno"          # Column for the new 'geno' variable
  ) %>%
  select(name, chr = CHROM, pos = POS, geno) # Rename and select columns

long_genotype<-as.data.frame(long_genotype)

long_genotype<-long_genotype %>% mutate(chr=str_replace(chr,"chr",""))

df.bed <- read.table(peaks_path)
names(df.bed) <- c("chr", "start","end", "peak")

#remove positions if there is only one SNP
df.bed <- df.bed %>% 
  mutate(lg = end- start) %>% 
  filter(lg > 0)

#load the top p values (filtered > 0.1) to plot the signal with the other plots I generate below
df.logp <- read.table(logp_path)

```

### Load the Population Genetics Statistics
```{r}
pixy_df <- list()

tajd_df<-fread(tajd_file)

tajd_df<-tajd_df %>% arrange(pop1,CHROM,BIN_START)

tajd_df <- tajd_df %>%
    mutate(window_pos_1=BIN_START+1) %>%
    mutate(window_pos_2=BIN_START+5000) %>%
    mutate(chromosome=CHROM) %>%
    mutate(statistic="avg_tajd") %>%
    mutate(value=TajimaD) %>%
    mutate(pop2=NA) %>%
    select(pop1,  pop2, chromosome, window_pos_1, window_pos_2, statistic, value, ) %>%
    arrange(pop1,  pop2, chromosome, window_pos_1)

df_pi <- fread(pi_file)
      
df_pi <- df_pi %>%
  gather(-pop, -window_pos_1, -window_pos_2, -chromosome,
  key = "statistic", value = "value") %>%
  mutate(pop1= pop) %>%
  mutate(pop2 = NA) %>%
  select(pop1, chromosome, window_pos_1, window_pos_2, statistic, value, pop2 )

fst_df <- fread(fst_file)

fst_df <- fst_df %>%
        gather(-pop1, -pop2, -window_pos_1, -window_pos_2, -chromosome,
               key = "statistic", value = "value")
      
dxy_df <- fread(dxy_file)

dxy_df <- dxy_df %>%
        gather(-pop1, -pop2, -window_pos_1, -window_pos_2, -chromosome,
               key = "statistic", value = "value")
      
      
pixy_df[[1]] <- fst_df
pixy_df[[2]] <- dxy_df
pixy_df[[3]] <- df_pi
pixy_df[[4]] <- tajd_df

pixy<-bind_rows(pixy_df) %>%
    arrange(pop1, pop2, chromosome, window_pos_1, statistic)


pixy<-pixy %>% pivot_wider(names_from=statistic,values_from=value) %>% mutate(comparison=paste0(pop1,"_",pop2))

pixy<-pixy %>% group_by(comparison) %>% mutate(zfst=((avg_wc_fst-mean(avg_wc_fst,na.rm=T))/sd(avg_wc_fst,na.rm=T)))

pixy <- pixy %>% 
  pivot_longer(cols = -c(pop1, pop2, chromosome, window_pos_1, window_pos_2,comparison),
               names_to = "statistic", values_to = "value")

rm(df_pi,dxy_df,fst_df,pixy_df,tajd_df)
gc()

pixy <- pixy %>%
  mutate(region_status = case_when(
    chromosome %in% df.bed$chr & window_pos_1 >= df.bed$start[match(chromosome, df.bed$chr)] & 
      window_pos_2 <= df.bed$end[match(chromosome, df.bed$chr)] ~ "Inside",
    TRUE ~ "Outside"
  ))
```

### Load Phenotypic Data
```{r}

load(file.path(root,"output_data/05_PopGen/",paste0(params$popgen_prefix,"_pop_phenos.Rda")))

phenotypes <- data.frame(
  POP = c("MOV","BIR","DOG","DOV","BAVA","BIK","APA","BEN"),
  population_phenotype = c("TP", "BP", "TP","TP","BP","BP","TP","TP")
)

phenotypes <- data.frame(
  POP = c("APA","BEN","BAM"),
  population_phenotype = c("TP", "TP", "BP")
)

```

### Filter Population Genetics Statistics
```{r}

# Dynamically create the filter condition
filter_expr <- paste0("pop1 == '", params$pops, "'", collapse = " | ")

# Generate all pairwise combinations
pairs <- combn(params$pops, 2, simplify = FALSE)

# Create forward comparisons
forward <- sapply(pairs, function(x) paste(x, collapse = "_"))

# Create backward comparisons
backward <- sapply(pairs, function(x) paste(rev(x), collapse = "_"))

# Combine forward and backward comparisons
comparison_list <- c(forward, backward)

comparision_expr <- paste0("comparison == '", comparison_list, "'", collapse = " | ")

pi_plot <- pixy %>%
  filter(statistic == "avg_pi", !is.na(value)) %>%
  filter(!!rlang::parse_expr(filter_expr)) %>%
  mutate(value = as.numeric(value)) %>%
  left_join(phenotypes, by = c("pop1" = "POP")) %>%
  dplyr::rename(phenotype_pop1 = population_phenotype)

tajd_plot<-pixy %>%
    filter(statistic == "avg_tajd", !is.na(value)) %>%
    filter(!!rlang::parse_expr(filter_expr)) %>%
    mutate(value = as.numeric(value) ) %>%  
    left_join(phenotypes, by = c("pop1" = "POP")) %>%
    dplyr::rename(phenotype_pop1 = population_phenotype)

fst_plot <- pixy %>%
  filter(statistic == "avg_wc_fst", !is.na(value)) %>%
  filter(!!rlang::parse_expr(comparision_expr)) %>%
  mutate(value = as.numeric(value)) %>%
  left_join(phenotypes, by = c("pop1" = "POP")) %>%
  dplyr::rename(pop1_phenotype = population_phenotype) %>%
  left_join(phenotypes, by = c("pop2" = "POP")) %>%
  dplyr::rename(pop2_phenotype = population_phenotype) %>%
  mutate(
    comparison_classification = case_when(
      pop1_phenotype == pop2_phenotype ~ "Same phenotype",
      pop1_phenotype != pop2_phenotype ~ "Different phenotypes",
      TRUE ~ "Unknown"
    )) %>%
  mutate(
    compare_color = case_when(
      comparison_classification == "Same phenotype" & pop1_phenotype=="BP" ~ "BP-BP",
      comparison_classification == "Same phenotype" & pop1_phenotype=="TP" ~ "TP-TP",
      comparison_classification == "Different phenotypes" ~ "BP-TP"
    )
  )
  

```

### Load SNP Data
```{r}
anno_file<-file.path(root,"input_data","00_Reference_Genome","jordan-mic4273-mb-hirise-20xx3__06-13-2024__final_assembly.fasta.renamed.sorted.genes_only.gff")
feat_table_file<-file.path(root,"input_data","00_Reference_Genome","GCF_002872115.1_PKINGS_0.1_feature_table.txt")
gemma_file<-file.path(root,"output_data","06_Association",params$data_path,paste0(params$data_path,".lmm2.assoc.txt"))
minpath<-file.path(root,"output_data","06_Association",params$data_path,paste0(params$data_path,"_permution"),"min.txt")
ldpath<-file.path(root,"output_data","06_Association",params$data_path,paste0(params$data_path,"_index_snps.ld.ld"))
peak_data_path<-file.path(root,"output_data","06_Association",params$data_path)

annotations<-import(anno_file)
strand(annotations)<-"*"


feat_table<-fread(feat_table_file)
pk.lmm<- gemma.order(gemma_file, "p_lrt")
min_data<-read.csv(minpath,header=F,sep="\t")
pvals<-sort(min_data$V10, decreasing = F)
significant = -log10(pvals[length(pvals) - floor(length(pvals)*0.95)])
suggestive = -log10(pvals[length(pvals) - floor(length(pvals)*0.67)])


#remove low log p to reduce memory footprint
pk.lmm.filt <- pk.lmm %>% filter(log_p > 1) %>% filter(af > params$MAF_thresh) %>% filter((!grepl("ups", chr)) & !is.na(row) & !is.na(log_p)) %>% arrange(numeric_chr)

pk.lmm.filt<- pk.lmm.filt %>% mutate(new_rs = str_split(rs, ":", simplify = TRUE)[, 1])

ld_data<-fread(ldpath)
gwas_ld_data<-merge(ld_data,pk.lmm.filt,by.x="SNP_B",by.y="new_rs")


pk.lmm.peaks.out<-read.table(file.path(peak_data_path,paste0(params$data_path,"_SNPS_IN_PEAKS.txt")),header=T)

index_snps <- pk.lmm.peaks.out %>%
  group_by(peak) %>%
  # Filter for rows with the maximum log_p value within each peak
  filter(log_p == max(log_p)) %>%
  # Sample one row randomly in case of ties
  slice_sample(n = 1) %>%
  ungroup() %>% # Remove the grouping structure
  mutate(new_rs = str_split(rs, ":", simplify = TRUE)[, 1])

index_snps_simp<-index_snps[,c(16,17,1,3,10)]
colnames(index_snps_simp)<-c("PEAK","SNP_A","CHR_A","BP_A","p_lrt")
index_snps_simp$maximum<-index_snps_simp$BP_A+75000
index_snps_simp$minimum<-index_snps_simp$BP_A-75000

gwas_ld_data<-merge(gwas_ld_data,index_snps_simp[,1:2],by.x="SNP_A",by.y="SNP_A")

snp_gr <- GRanges(
  seqnames = index_snps_simp$CHR_A,
  ranges = IRanges(start = index_snps_simp$minimum, end = index_snps_simp$maximum),
)

mcols(snp_gr)$PEAK <- index_snps_simp$PEAK

# Perform the overlap
overlaps <- findOverlaps(snp_gr, annotations, ignore.strand = TRUE)

# Create a mapping table from overlaps
overlap_mapping <- data.frame(
  peak_index = queryHits(overlaps),
  annotation_index = subjectHits(overlaps)
)

overlap_mapping$PEAK <- mcols(snp_gr)$PEAK[overlap_mapping$peak_index]

# Convert annotations to a dataframe
overlapping_annotations_df <- as.data.frame(annotations)

# Ensure there's a unique identifier for each annotation
overlapping_annotations_df$unique_id <- seq_len(nrow(overlapping_annotations_df))

# Filter overlap_mapping to include only unique annotation indices
overlap_mapping_unique <- overlap_mapping[!duplicated(overlap_mapping$annotation_index), ]

# Merge SNP_A into overlapping_annotations_df
overlapping_annotations_df <- merge(overlapping_annotations_df, overlap_mapping_unique, by.x = "unique_id", by.y = "annotation_index", all.x = TRUE)
overlapping_annotations_df<-subset(overlapping_annotations_df,!is.na(PEAK))
```

```{r}
fish_data_file<-file.path(root,"input_data/01_Terra/data_model/fish_data_2024a.txt")
```


```{r}
fish_data_file<-file.path(root,"input_data/01_Terra/data_model/fish_data_2024a.txt")

fish_data<-read.csv(fish_data_file,row.names=1,sep="\t")

pheno_discrete <- fish_data %>% 
  mutate(Phenotype = factor(Phenotype)) %>%
  select(Phenotype)

phenos<-setNames(as.character(pheno_discrete$Phenotype), row.names(pheno_discrete))
phenos <- gsub("TYPE_II", "TP", phenos)
phenos <- gsub("TYPE_I", "TP", phenos)
phenos<-as.factor(phenos)
## set colors for plotting 
col.pheno<-setNames(c("blue","red","purple"),levels(phenos)) 

phenos_df <- data.frame(Sample = names(phenos), Phenotype = as.factor(phenos))
```

## Plotting

### Plot Genotype Matrix
```{r}
for (peak.idx in unique(df.bed$peak)) {
  
  # Take bed file, pull out peak of interest then filter by it
  df.bed.idx <- df.bed %>% filter(peak == peak.idx)
  chr.idx <- unique(df.bed.idx$chr)
  print(paste0("running ", peak.idx, " on ", chr.idx))
  
  # Subset geno df by the peak region 
  df.genos.sub <- long_genotype %>% 
    filter(chr == chr.idx & pos > min(df.bed.idx$start) & pos < max(df.bed.idx$end)) %>%
    arrange(name, pos) %>%  # Sort by name and then by position
    group_by(name) %>%
    mutate(snp_order_within_individual = row_number()) %>%  # Create sequence number
    ungroup()
  
  df.genos.sub$geno <- factor(ifelse(is.na(df.genos.sub$geno), "NA", as.character(df.genos.sub$geno)),
                              levels = c("NA", "0", "1", "2"))
  
  # Step 1: Merge phenotype information
  df.genos.sub <- df.genos.sub %>%
    mutate(population = sub("_.*", "", name)) %>%  # Extract population from the name
    left_join(phenos_df, by = c("name" = "Sample"))  # Merge phenos_df to include Phenotype
  
  # Step 2: Sort by phenotype within each population
  df.genos.sub <- df.genos.sub %>%
    group_by(population) %>%
    arrange(Phenotype, name, .by_group = TRUE) %>%  # Sort by Phenotype and then name within each population
    ungroup() %>%
    mutate(name = factor(name, levels = rev(unique(name))))  # Reverse levels for top-to-bottom plotting
  
  # Step 3: Identify the first individual (top-to-bottom) for each population
  first_individuals <- df.genos.sub %>%
    group_by(population) %>%
    slice_head(n = 1) %>%  # Select the first individual per population
    select(name, population)  # Keep only the name and population
  
  # Create a mapping for y-axis labels: Label only the first individual per population
  label_mapping <- setNames(first_individuals$population, first_individuals$name)
  
  # Step 4: Create the ggplot object
  p <- ggplot() +
    # Plot the phenotype column
    geom_tile(data = df.genos.sub,
              aes(x = -1, y = name, fill = Phenotype),  # Use a separate column for phenotype
              width = 1, height = 1) +
    # Plot the genotypes
    geom_tile(data = df.genos.sub,
              aes(x = snp_order_within_individual, y = name, fill = geno)) +
    # Set fill scales for genotype and phenotype
    scale_fill_manual(name = "Genotype/Phenotype",
                      values = c(col.pheno, "NA" = "white", "0" = "grey", "1" = "#1a80bb", "2" = "#f2c45f")) +
    labs(title = paste0("Peak ", peak.idx, " on Chr ", chr.idx),
         x = "SNP Order within Individual", 
         y = "Individual",
         fill = "Genotype") +
    scale_y_discrete(labels = function(names) {
      # Only label the first individual per population
      ifelse(names %in% names(label_mapping), label_mapping[names], "")
    }) +
    scale_x_continuous(expand = c(0, 0), limits = c(-2, max(df.genos.sub$snp_order_within_individual) + 1)) +
    theme_minimal() +
    theme(panel.grid = element_blank())
  
  # Step 5: Save the plot
  ggsave(file.path(root, "output_data", "08_Peak_Analysis", params$data_path, 
                   paste0(params$data_path, "_PEAK", peak.idx, "_CHR", chr.idx, ".png")), 
         plot = p, width = 8.5, height = 17)
}


```
### Another Approach to Plotting Genotypes

```{r}
for (peak.idx in unique(df.bed$peak)) {
  
  # Take bed file, pull out peak of interest then filter by it
  df.bed.idx <- df.bed %>% filter(peak == peak.idx)
  chr.idx <- unique(df.bed.idx$chr)
  print(paste0("running ", peak.idx, " on ", chr.idx))
  
  # Subset geno df by the peak region 
  df.genos.sub <- long_genotype %>% 
    filter(chr == chr.idx & pos > min(df.bed.idx$start) & pos < max(df.bed.idx$end)) %>%
    arrange(name, pos) %>%  # Sort by name and then by position
    group_by(name) %>%
    mutate(snp_order_within_individual = row_number()) %>%  # Create sequence number
    ungroup()
  
  df.genos.sub$geno <- factor(ifelse(is.na(df.genos.sub$geno), "NA", as.character(df.genos.sub$geno)),
                              levels = c("NA", "0", "1", "2"))
  
  # Step 1: Extract the population and ensure plotting order
df.genos.sub <- df.genos.sub %>%
  mutate(population = sub("_.*", "", name)) %>%  # Extract population from the name
  arrange(name) %>%  # Sort individuals by name
  mutate(name = factor(name, levels = rev(unique(name))))  # Reverse the levels for top-to-bottom plotting

  
  # Step 2: Identify the first individual (from top to bottom) for each population
  first_individuals <- df.genos.sub %>%
    group_by(population) %>%
    slice_head(n = 1) %>%  # Select the first individual per population
    select(name, population)  # Keep only the name and population
  
  # Create a mapping for y-axis labels: Label only the first individual per population
  label_mapping <- setNames(first_individuals$population, first_individuals$name)
  
  # Step 3: Create the ggplot object
  p <- ggplot(df.genos.sub, aes(x = snp_order_within_individual, y = name, fill = geno)) +
    geom_tile() +
    scale_fill_manual(values = c("NA" = "white", "0" = "grey", "1" = "#1a80bb", "2" = "#f2c45f")) +
    labs(title = paste0("Peak ", peak.idx, " on Chr ", chr.idx),
         x = "SNP Order within Individual", 
         y = "Individual",
         fill = "Genotype") +
    scale_y_discrete(labels = function(names) {
      # Only label the first individual per population
      ifelse(names %in% names(label_mapping), label_mapping[names], "")
    }) +
    theme_minimal() +
    theme(panel.grid = element_blank())
  
  # Step 4: Save the plot
  ggsave(file.path(root, "output_data", "08_Peak_Analysis", params$data_path, 
                   paste0(params$data_path, "_PEAK", peak.idx, "_CHR", chr.idx, ".png")), 
         plot = p, width = 8.5, height = 17)
}


```


### Alternative Approach to Plotting Genotypes
```{r}
for (peak.idx in unique(df.bed$peak)) {
  
  # Filter bed file for peak of interest
  df.bed.idx <- df.bed %>% filter(peak == peak.idx)
  chr.idx <- unique(df.bed.idx$chr)
  print(paste0("Running ", peak.idx, " on ", chr.idx))
  
  # Subset genotype data
  df.genos.sub <- long_genotype %>%
    filter(chr == chr.idx & pos > min(df.bed.idx$start) & pos < max(df.bed.idx$end)) %>%
    arrange(name, pos) %>%
    group_by(name) %>%
    mutate(snp_order_within_individual = row_number()) %>%
    ungroup()
  
  df.genos.sub$geno <- factor(ifelse(is.na(df.genos.sub$geno), "NA", as.character(df.genos.sub$geno)),
                              levels = c("NA", "0", "1", "2"))
  
  # Create a wide-format matrix for clustering
  geno_matrix <- df.genos.sub %>%
    pivot_wider(id_cols = name, names_from = snp_order_within_individual, values_from = geno, values_fill = "NA") %>%
    column_to_rownames("name") %>%
    mutate_all(as.numeric)
  
  # Compute a distance matrix and perform hierarchical clustering
  geno_dist <- dist(geno_matrix, method = "euclidean")  # Use appropriate distance metric
  geno_hclust <- hclust(geno_dist, method = "ward.D2")  # Hierarchical clustering
  
  # Reorder rows based on clustering
  ordered_rows <- rownames(geno_matrix)[geno_hclust$order]
  
  df.genos.sub <- df.genos.sub %>%
    mutate(name = factor(name, levels = ordered_rows))
  
  # Plot the clustered heatmap
  p <- ggplot(df.genos.sub, aes(x = snp_order_within_individual, y = name, fill = geno)) +
    geom_tile() +
    scale_fill_manual(values = c("NA" = "white", "0" = "grey", "1" = "#1a80bb", "2" = "#f2c45f")) +
    labs(title = paste0("Peak ", peak.idx, " on Chr ", chr.idx),
         x = "SNP Order within Individual", 
         y = "Individual",
         fill = "Genotype") +
    theme_minimal() +
    theme(panel.grid = element_blank())
  
  # Save the plot
  ggsave(file.path(root, "output_data", "08_Peak_Analysis", params$data_path, 
                   paste0(params$data_path, "_PEAK", peak.idx, "_CHR", chr.idx, ".png")), 
         plot = p, width = 8.5, height = 17)
}
```



### Plot Popgen Boxplots 
```{r}
df.bed$chr<-paste0("chr",df.bed$chr)

# Generate the plot
pp<-ggplot(pi_plot, aes(x = region_status, y = value, fill = phenotype_pop1)) +
  geom_boxplot(outlier.shape = NA) +
  scale_fill_manual(values = c("BP" = "skyblue3", "TP" = "coral2")) +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.minor.y = element_blank(),
    panel.background = element_blank(),
    axis.text = element_text(size = rel(1.2), family = "Arial"),
    axis.title.x = element_text(size = rel(2.1), family = "Arial", margin = margin(t = 20)),
    axis.title.y = element_text(size = rel(2.1), family = "Arial", margin = margin(r = 20))
  ) +
  scale_y_continuous(limits = c(0, .01), breaks = c(0, 0.005, 0.01), labels = percent_format()) +
  xlab("Population") +
  ylab("π (% Nucleotide Diversity) ")

td<-pixy %>%
    filter(statistic == "avg_tajd", !is.na(value)) %>%
    filter(pop1=="APA" | pop1=="BAM" | pop1=="BEN") %>%
    mutate(value = as.numeric(value) ) %>%  
    left_join(phenotypes, by = c("pop1" = "POP")) %>%
    dplyr::rename(phenotype_pop1 = population_phenotype) %>% ggplot(aes(x = region_status, y = value, fill = phenotype_pop1)) +
    geom_boxplot(outlier.shape = NA) +
    scale_fill_manual(values = c("BP" = "skyblue3", "TP"="coral2", "mixed" = "mediumorchid1")) +
    theme_minimal() +
    theme(
        legend.position = "bottom",
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.background = element_blank(),
        axis.text = element_text(size = rel(1.2), family = "Arial"),
        axis.title.x = element_text(size = rel(2.1), family = "Arial", margin = margin(t = 20)),  # Adjust margin for x-axis title
        axis.title.y = element_text(size = rel(2.1), family = "Arial", margin = margin(r = 20))   # Adjust margin for y-axis title
    ) +
    scale_y_continuous(limits = c(-2, 4), breaks=c(-2,0,2,4)) +
    xlab("Population") +
    ylab("Tajima's D") 

# Step 4: Create the plot
fp<-ggplot(fst_plot, aes(x = comparison, y = value, fill = region_status)) +
  geom_boxplot(outlier.shape = NA) +
  scale_fill_manual(values = c("Inside" = "skyblue3", "Outside"="coral2")) +
  theme_minimal() +
  theme(
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.minor.y = element_blank(),
    panel.background = element_blank(),
    strip.text.x = element_text(size = rel(2.1)),
    axis.text = element_text(size = rel(1.2), family = "Arial",angle = 90, hjust = 1),
    axis.title.x = element_text(size = rel(2.1), family = "Arial", margin = margin(t = 20)),  # Adjust margin for x-axis title
    axis.title.y = element_text(size = rel(2.1), family = "Arial", margin = margin(r = 20))   # Adjust margin for y-axis title
  ) +
  scale_y_continuous(breaks = c(0, 0.5, 1)) +
  ylim(0, 1) +
  xlab("Comparison") +
  ylab("Weir & Cockerham's Fst") +
  theme(legend.position = "bottom")

```

```{r, fig.height=12, fig.width=8}

combined_plot <- pp / td / fp 

combined_plot <- combined_plot + 
                 plot_annotation(tag_levels = 'A') &
                 theme(plot.tag = element_text(size = 48, face="bold"))

# Adjust relative heights of the plots to change the overall aspect ratio
# Increase the values to make the plots taller
combined_plot <- combined_plot + 
                 plot_layout(heights = c(2, 2, 2)) 

# Print the combined plot

plot_name<-file.path(root,'output_data/08_Peak_Analysis/',params$data_path,'peak_stats.svg')
svg(plot_name, width=12, height = 24)  # Adjust width as needed
combined_plot
n<-dev.off()
```



```{r}
# Main loop
for (peak.idx in unique(df.bed$peak)) {
  df.bed.idx <- df.bed %>% filter(peak == peak.idx)
  chr.idx <- unique(df.bed.idx$chr)
  start <- min(df.bed.idx$start)
  end <- max(df.bed.idx$end)
  
  pi_peak <- filter_data(pi_plot, chr.idx, start,end,window_size = 100000)
  tpp_plot <- filter_data(tajd_plot, chr.idx, start,end,window_size = 100000)
  fpp_plot <- filter_data(fst_plot, chr.idx, start,end,window_size = 100000)
  
  idx_snp_peak<-index_snps_simp %>% filter(CHR_A == chr.idx & BP_A >= min(df.bed.idx$start)-100000 & BP_A <= min(df.bed.idx$start)+100000)
  
  # Create each plot
  spp <- create_gwas_plot(pk.lmm, gwas_ld_data, idx_snp_peak, overlapping_annotations_df, chr.idx, start,end,window_size = 100000)
  ppp <- create_pi_plot(pi_peak, df.bed.idx, chr.idx)
  tpp <- create_tajima_plot(tpp_plot, df.bed.idx, chr.idx)
  fpp <- create_fst_plot(fpp_plot, df.bed.idx, chr.idx)
  
  combined_peak_plot <- spp / ppp / tpp / fpp +
    plot_annotation(paste0("Peak ", peak.idx), tag_levels = 'A') &
    theme(plot.tag = element_text(size = 48, face = "bold"))
  
  # Adjust relative heights of the plots
  combined_peak_plot <- combined_peak_plot + plot_layout(heights = c(2, 2, 2, 2))
  
  ggsave(
    file.path(root, "output_data", "08_Peak_Analysis", params$data_path,
              paste0(params$data_path, "_PEAK", peak.idx, "_CHR", chr.idx, "_peak_stats_plot.png")),
    plot = combined_peak_plot, width = 8.5, height = 17
  )
  }
```
